### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by pims** [cloudflare/ipvs#10]
https://github.com/cloudflare/ipvs/blob/master/client.go#L115

Should this be `Masquerade` instead?

**Comment by terinjokes** [comment]
Yeah, but will need another semver bump.

**Comment by Chainyinghao** [comment]
My destination's address is ipv4,but when I use destination.Address,it's ipv6,why?
![image](https://github.com/cloudflare/ipvs/assets/41147624/11dbc0ca-27cf-4a99-9b78-3dcfc7acd73c)
